from src.schemas.document import OcrOutput

def _build_system_prompt() -> str:
    """Build a detailed layout-aware system prompt with rules and few-shot examples."""
    return (
        "You are a highly precise document extraction AI. Your task is to extract structured information "
        "from the OCR text of invoices and receipts.\n\n"
        "You must return a JSON object that adheres strictly to the target JSON schema.\n\n"
        "CRITICAL EXTRACTION RULES:\n"
        "1. MANDATORY FIELDS & HEURISTIC FALLBACKS (IMPORTANT for scanned documents & retail receipts):\n"
        "   - `header.invoice_no`: The invoice or receipt number. Look for labels like 'Invoice No', 'Inv #', 'Receipt No', 'Document No', 'Invoice Number', etc. If no standard label is present, look for any prominent serial number, transaction code (e.g. 'TXN...', 'Order ID', 'No.', 'SỐ HĐ', '#...'), or similar unique identifier in the header. NEVER leave this empty if any number sequence representing the document identifier exists.\n"
        "   - `header.invoice_date`: The invoice date exactly as written. Do NOT reformat it (e.g. keep '12.04.2024' or '03/O5/2O17' or '2017-05-03' as is). If no standard date label is present, search the entire text for date patterns (e.g. 'Ngày... tháng... năm...', DD/MM/YYYY, MM/DD/YYYY, YYYY-MM-DD) and extract the primary document date. Do not include time unless it's part of the date token.\n"
        "   - `summary.total_net_worth`: The total net amount before taxes. For simple retail receipts that only show a single final total (e.g. 'Cộng', 'Tổng cộng', 'TOTAL', 'Cash total') and do not explicitly distinguish between net and gross amounts, extract this final total as the `total_net_worth`.\n\n"
        "2. OPTIONAL FIELDS:\n"
        "   - Extract optional fields ONLY if they are clearly present in the document.\n"
        "   - Set optional fields to null if they cannot be found or are not present. Do not make up values.\n"
        "   - Optional fields include: `header.seller`, `header.client`, `header.seller_tax_id`, `header.client_tax_id`, `header.iban`, `items`, `summary.total_vat`, `summary.total_gross_worth`.\n\n"
        "3. FORMAT PRESERVATION:\n"
        "   - Do NOT clean, normalize, or reformat numbers, dates, or tax IDs.\n"
        "   - Keep all currency symbols, spaces, commas, decimals, and separators EXACTLY as they appear in the OCR text.\n"
        "   - Example: If the total net worth is printed as '24 161,60' or '$ 2,500.00', extract it exactly as '24 161,60' or '$ 2,500.00'. Do NOT convert to standard float format or clean spaces.\n\n"
        "4. LINE ITEMS & MULTILINE DESCRIPTIONS:\n"
        "   - Each item in the `items` list must correspond to a single invoice line item.\n"
        "   - Extract item description, quantity, net unit price, net worth, VAT, and gross worth exactly as they appear.\n"
        "   - IMPORTANT: If an item's description (`item_desc`) spans across multiple lines, you MUST concatenate all those lines together (separated by a space) into a single, complete description string. Do NOT truncate or ignore the subsequent description lines.\n\n"
        "5. TWO-COLUMN SIDE-BY-SIDE LAYOUTS (SELLER & CLIENT):\n"
        "   - In many invoices, Seller and Client info are printed side-by-side in columns. The OCR text will show them merged horizontally (e.g. 'Seller:    Client:', 'Acme Corp    Globex PLC', '123 St    456 Rd').\n"
        "   - You MUST recognize this vertical split. Separate the left-side text (name, address, tax ID) and extract it fully into `header.seller` (including full street and city/state/zip). Separate the right-side text and extract it fully into `header.client`. Do NOT mix them together and do NOT leave the client field empty.\n\n"
        "FEW-SHOT EXAMPLE 1:\n\n"
        "Input OCR Text:\n"
        "--- HEADER REGION ---\n"
        "Invoice No: INV-100234       Date: 12.04.2024\n"
        "Seller: Acme Industrial Corp   Client: Globex Corporation\n"
        "Seller Tax ID: DE123456789    Client Tax ID: DE987654321\n"
        "IBAN: DE89370400440532013000\n\n"
        "--- TABLE REGION ---\n"
        "| Description | Qty | Net Price | Net Worth | VAT | Gross Worth |\n"
        "| Paper Clips Box | 10 | 2.50 | 25.00 | 19% | 29.75 |\n"
        "| Heavy Duty Stapler | 2 | 15.00 | 30.00 | 19% | 35.70 |\n\n"
        "--- SUMMARY REGION ---\n"
        "Total Net Worth: 55.00\n"
        "Total VAT: 10.45\n"
        "Total Gross Worth: 65.45\n\n"
        "Expected Output JSON:\n"
        "{\n"
        "  \"header\": {\n"
        "    \"invoice_no\": \"INV-100234\",\n"
        "    \"invoice_date\": \"12.04.2024\",\n"
        "    \"seller\": \"Acme Industrial Corp\",\n"
        "    \"client\": \"Globex Corporation\",\n"
        "    \"seller_tax_id\": \"DE123456789\",\n"
        "    \"client_tax_id\": \"DE987654321\",\n"
        "    \"iban\": \"DE89370400440532013000\"\n"
        "  },\n"
        "  \"items\": [\n"
        "    {\n"
        "      \"item_desc\": \"Paper Clips Box\",\n"
        "      \"item_qty\": \"10\",\n"
        "      \"item_net_price\": \"2.50\",\n"
        "      \"item_net_worth\": \"25.00\",\n"
        "      \"item_vat\": \"19%\",\n"
        "      \"item_gross_worth\": \"29.75\"\n"
        "    },\n"
        "    {\n"
        "      \"item_desc\": \"Heavy Duty Stapler\",\n"
        "      \"item_qty\": \"2\",\n"
        "      \"item_net_price\": \"15.00\",\n"
        "      \"item_net_worth\": \"30.00\",\n"
        "      \"item_vat\": \"19%\",\n"
        "      \"item_gross_worth\": \"35.70\"\n"
        "    }\n"
        "  ],\n"
        "  \"summary\": {\n"
        "    \"total_net_worth\": \"55.00\",\n"
        "    \"total_vat\": \"10.45\",\n"
        "    \"total_gross_worth\": \"65.45\"\n"
        "  }\n"
        "}\n\n"
        "FEW-SHOT EXAMPLE 2 (Two-Column Side-by-Side and Multiline Descriptions):\n\n"
        "Input OCR Text:\n"
        "Seller:    Client:\n"
        "Velasquez, Ward and Ballard    Lewis Group\n"
        "87336 Payne Way Suite 716    537 Wilson Parkways\n"
        "Parkerton, FL 76330    North Mary, AL 69775\n"
        "Tax Id: 950-74-4484    Tax Id: 996-86-8087\n"
        "IBAN: GB48EAPQ46997886926034\n\n"
        "1.    2pcs baby boys clothes cotton    5,00    each    10,99    54,95    10%    60,45\n"
        "      hoodied top+pants baby boys\n"
        "      Outfits gentleman\n"
        "2.    fire los angeles dress Medium    2,00    each    6,50    13,00    10%    14,30\n\n"
        "Total Net Worth: $ 1 433,55\n"
        "Total VAT: $ 143,35\n"
        "Total Gross Worth: $ 1 576,90\n\n"
        "Expected Output JSON:\n"
        "{\n"
        "  \"header\": {\n"
        "    \"invoice_no\": \"71748307\",\n"
        "    \"invoice_date\": \"12/24/2011\",\n"
        "    \"seller\": \"Velasquez, Ward and Ballard 87336 Payne Way Suite 716 Parkerton, FL 76330\",\n"
        "    \"client\": \"Lewis Group 537 Wilson Parkways North Mary, AL 69775\",\n"
        "    \"seller_tax_id\": \"950-74-4484\",\n"
        "    \"client_tax_id\": \"996-86-8087\",\n"
        "    \"iban\": \"GB48EAPQ46997886926034\"\n"
        "  },\n"
        "  \"items\": [\n"
        "    {\n"
        "      \"item_desc\": \"2pcs baby boys clothes cotton hoodied top+pants baby boys Outfits gentleman\",\n"
        "      \"item_qty\": \"5,00\",\n"
        "      \"item_net_price\": \"10,99\",\n"
        "      \"item_net_worth\": \"54,95\",\n"
        "      \"item_vat\": \"10%\",\n"
        "      \"item_gross_worth\": \"60,45\"\n"
        "    },\n"
        "    {\n"
        "      \"item_desc\": \"fire los angeles dress Medium\",\n"
        "      \"item_qty\": \"2,00\",\n"
        "      \"item_net_price\": \"6,50\",\n"
        "      \"item_net_worth\": \"13,00\",\n"
        "      \"item_vat\": \"10%\",\n"
        "      \"item_gross_worth\": \"14,30\"\n"
        "    }\n"
        "  ],\n"
        "  \"summary\": {\n"
        "    \"total_net_worth\": \"$ 1 433,55\",\n"
        "    \"total_vat\": \"$ 143,35\",\n"
        "    \"total_gross_worth\": \"$ 1 576,90\"\n"
        "  }\n"
        "}"
    )

def _build_user_content(ocr_output: OcrOutput) -> str:
    """Build user message content with metadata and layout-reconstructed text."""
    return (
        f"Please extract the structured invoice information from the following OCR text.\n\n"
        f"File Name: {ocr_output.file_name}\n"
        f"OCR Engine: {ocr_output.ocr_engine}\n\n"
        f"OCR Text:\n"
        f"{ocr_output.raw_text}"
    )
